Updated with new content.
JamEnergy/PooArmory pull request #3
Opened 2020-05-28 21:55 UTC by jiglei

Items added:

- Milletian Weapon
- Milletian Armor
- The Boof of the Milletian
- Milletian Focus and Shield
- Red Kitty Necklace (Why not lol)
-105 Earrings (future equipment)

I added extra equipment type to make sure the milletian focus and shield can use the correct scrolls (Truth and Sealed)

Scrolls added:
Wish, Meaningful, Cold-blooded(Future ES)

2020-05-29 18:52 UTC, JamEnergy requested changes
Did you add new types for militian shield/focus to make the scrolls apply on the appropriate offhand items only? That has the correct effect, but I would for now prefer if you didn't create new item types (accepting the "bug" that you can put the new scrolls on old shields).

Could you make that change and re-submit?

I'll add something like a level or name filter to the scroll to fix the resultant bug of the scroll being applicable to items that it isn't meant to be.

Thanks for taking the effort to understand the code and add to the data, though.

2020-05-29 18:52 UTC, JamEnergy commented on data.js
> +		"milletianshield":true
milletianshield shouldn't be a type (just a name of an item), see below

2020-05-29 18:52 UTC, JamEnergy commented on data.js
> +		"milletianfocus":true
same as above

2020-05-29 18:52 UTC, JamEnergy commented on data.js
> +		"type":"milletianfocus",
type is wrong, the shining focus one was right though

2020-05-29 18:52 UTC, JamEnergy commented on data.js
> +		"type":"milletianshield",
type should just be smallshield

2020-05-29 20:01 UTC, jiglei commented
I'm sorry if this added categories look ugly, I'll revert it.

I'm not really skilled on this kind of stuff, just wanted to make something functional :)

2020-05-30 18:59 UTC, JamEnergy commented
Trailing commas are apparently okay in Javascript, although they are illegal JSON. I don't care enough to ask for that to be changed right now though.

2020-05-30 19:00 UTC, merged